[package]
name = "invest-web"
version = "0.1.0"
edition = "2021"
description = "Invest web project"
readme = "README.md"
repository = "https://github.com/yewstack/yew-trunk-minimal-template"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { version = "0.20" }
yew-router = { version = "0.17" }
yew-hooks = { version = "0.2.0" }
wasm-logger = "0.2"
tracing-wasm = "0.2"
parking_lot = "0.12.1"
console_error_panic_hook = "0.1.7"
tracing = "0.1"
gloo = "0.8.0"
thiserror = "1"
lazy_static = "1.4"
serde = "1"
serde-value = "0.7"
reqwest = { version = "0.11.7", features = ["json"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlInputElement",
]

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
opt-level = 'z'